-- Aegis 达梦初始化脚本（请用 SYSDBA 执行）
-- 1) 创建业务用户
CREATE USER "AEGIS_USER" IDENTIFIED BY "StrongPass_123";

-- 2) 授权（按最小权限可再收敛）
GRANT RESOURCE, PUBLIC, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE INDEX, CREATE SEQUENCE TO "AEGIS_USER";

-- 3) （可选）指定默认表空间
-- ALTER USER "AEGIS_USER" DEFAULT TABLESPACE MAIN;

-- 4) 创建独立 schema（可选）
-- CREATE SCHEMA "AEGIS" AUTHORIZATION "AEGIS_USER";
